spring:
  datasource:
    url: jdbc:h2:mem:youngTest
    driverClassName: org.h2.Driver
    username: sa
    password:
  # h2 setting info
  h2:
    console:
      enabled: true # 사용여부
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

kakao:
  api:
    key: "5dfdad8618a37c87924127904d16737c"
  secret:
    key: "RqPVsc3ivCKBW5fhU8jfGeu23aZPVO3J"
  redirect:
    uri : "http://localhost:8080/oauth/kakao"
