spring:
  output:
    ansi:
      enabled: ALWAYS
  # h2 setting info
  datasource:
    url: jdbc:h2:mem:youngTest # h2 접속정보
    driverClassName: org.h2.Driver # Database를 h2로 사용하겠다
    username: sa # 접속시 입력할 username
    password:
  h2:
    console:
      enabled: true # 사용여부
      path: /h2-console # H2 console path
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

logging:
  level:
    org.springframework.security: DEBUG

kakao:
  api:
    key: "a7af160f851b8eae1dd5895ee4bfbb50"
  redirect:
    uri : "http://localhost:8080/kakao/callback"
  logOutRedirect:
    uri : "http://localhost:8080/kakao/logout"

